# Generated by Django 6.0.1 on 2026-01-08 18:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import sale_record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_path', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Invoice Storage'), (2, 'Other')], default=1)),
            ],
            options={
                'verbose_name': 'Store Default path',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name')),
                ('address_one', models.TextField(blank=True, null=True, verbose_name='Address Line 1')),
                ('address_two', models.TextField(blank=True, null=True, verbose_name='Address Line 2')),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal Code')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_record.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_record.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_record.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of the customer who is purchasing', max_length=255, verbose_name='Customer Name')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter Phone Number with country code: i.e. +919988776655', max_length=128, null=True, region=None, verbose_name='Contact Number')),
                ('alternate_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter Phone Number with country code: i.e. +919988776655', max_length=128, null=True, region=None, verbose_name='Alternate Contact Number')),
                ('email_address', models.EmailField(blank=True, help_text='i.e. example@domain.com', max_length=254, null=True, verbose_name='Email Address')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, help_text='Address', null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_record.address', verbose_name='Postal Address')),
            ],
            options={
                'verbose_name': 'Customer detail',
                'verbose_name_plural': 'Customer Details',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleEffectiveCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qty.')),
                ('discount', models.IntegerField(default=0)),
                ('imei', models.CharField(blank=True, help_text='Enter unique IMEI or barcode generated by Manufacturer', max_length=30, null=True, verbose_name='IMEI Number')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.productrecord')),
            ],
            options={
                'verbose_name': 'Effective cost of Mobile',
                'verbose_name_plural': 'Effective cost of Mobile',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter date of purchase/invoice', null=True, verbose_name='Sale Date')),
                ('delivery_date', models.DateField(blank=True, help_text='Date of order delivered', null=True)),
                ('payment_mode', models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Card'), (4, 'Online Transfer NEFT/RTGS'), (5, 'Credit/EMI/Loan')], null=True)),
                ('cancelled', models.BooleanField(default=False, help_text='mark if bill cancelled', verbose_name='Cancelled/Refunded')),
                ('payment_status', models.BooleanField(default=False, help_text="mark if payment isn't processed immediately", verbose_name='Payment Status (in transit/dispute)')),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date of full payment', null=True, verbose_name='Payment Date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.CharField(blank=True, default=sale_record.models.increment_invoice_number, help_text='Enter Order/Invoice Number', max_length=500, null=True, verbose_name='Enter Invoice Number')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale_record.customerdetail')),
                ('items', models.ManyToManyField(to='sale_record.saleeffectivecost')),
            ],
            options={
                'verbose_name': 'Sale record',
                'verbose_name_plural': 'Sale Records',
                'abstract': False,
            },
        ),
    ]
